baseurl = "https://blog.upinus.dev"
languageCode = "en"
title = "Upinus Tech Blog"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/upinus\">Upinus</a> 2019"
disqusShortname = "shortname"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params.features]
disqusOnDemand = true  # Load Disqus comments on click

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Bao Ho" # Site author's full name
authorEmail = "hogiabaor@gmail.com"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "Upinus Tech Blog" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = ""
github = "upinus"
email = ""
linkedin = ""
gitlab = ""
instagram = "__upinusdev"
codepen = ""
facebook = ""

[params.social.config]
platforms = ["twitter","github","email","linkedin","instagram"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

